server:
  port: 8080
spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://172.18.0.2:5432/stepuha}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: false
